global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout: 10s
    api_version: v1
scrape_configs:
- job_name: pushgateway
  honor_labels: true
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - pushgateway:9091